# Generated by Django 5.1.2 on 2024-10-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/bg.jpg', upload_to='media/blog/'),
        ),
    ]
