# Generated by Django 5.1.2 on 2024-10-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='menu/menu-1.jpg', upload_to='media/menu/')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('price', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('login_require', models.BooleanField(default=False)),
                ('published_date', models.DateTimeField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
