# Generated by Django 5.1.2 on 2024-10-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffe_app', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.ManyToManyField(to='coffe_app.category'),
        ),
    ]
