# Generated by Django 5.1.2 on 2024-11-02 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffe_app', '0005_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='person',
        ),
    ]
