# Generated by Django 5.1.2 on 2024-11-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffe_app', '0006_remove_reservation_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='person',
            field=models.IntegerField(choices=[(1, 'Person'), (2, 'Spade'), (3, 'Heart'), (4, 'Club')], default=2),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateTimeField(default=False),
        ),
    ]
