# Generated by Django 5.1.2 on 2024-11-02 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffe_app', '0007_reservation_person_alter_reservation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='person',
        ),
    ]
