# Generated by Django 5.1.2 on 2024-11-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffe_app', '0008_remove_reservation_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='choice_field',
            field=models.CharField(choices=[('person 1', 'person 1'), ('person 2', 'person 2'), ('person 3', 'person 3')], default='person 1', max_length=10),
        ),
    ]
